### PR TITLE
AI-878 : fixed Save button state

### PR DESCRIPTION
**Pull request by akbertram**
https://bedatadriven.atlassian.net/browse/AI-878

### CODE REVIEW

**Comment by akbertram** [comment]
@bddbot please rebuild

**Comment by akbertram** [comment]
@bddbot  please release this one too

**Comment by akbertram** [comment]
@yuriyz can you merge beta into this push the result to this branch?

**Comment by yuriyz** [comment]
@akbertram beta is merged into beta-ai-878.

**Pull request closed without merging**
