### PR TITLE
AI-877: When User goes to another tab without clicking on "save" button, system saves the changes automatically

### PR DESCRIPTION
**Pull request by bddbot**
[AI-877](https://bedatadriven.atlassian.net/browse/AI-877): When User goes to another tab without clicking on "save" button, system saves the changes automatically

When User goes to another tab without clicking on "save" button, system saves the changes automatically.

As per test case https://bdd.testrail.com/index.php?/tests/view/1866 we should NOT save changes until user clicks on the Save button.

Kindly check this Video: http://screencast.com/t/WMevb6l3jH0

### CODE REVIEW

**Comment by akbertram** [comment]
@bdd please rebuild

**Comment by akbertram** [comment]
@bddbot  please rebuild

**Comment by akbertram** [comment]
@bddbot please release

**Comment by akbertram** [comment]
@bddbot please rebuild

**Comment by akbertram** [comment]
@yuriyz can you fix the failing test so we can merge this PR?

**Comment by yuriyz** [comment]
@akbertram done

**Comment by akbertram** [comment]
@bddbot please rebuild

**Pull request closed without merging**
