### PR TITLE
AI-873: When user checks the checkboxes for Copy Partners and Copy User Permissions while creating a copy of the database, then system fails to create the database successfully

### PR DESCRIPTION
**Pull request by bddbot**
[AI-873](https://bedatadriven.atlassian.net/browse/AI-873): When user checks the checkboxes for Copy Partners and Copy User Permissions while creating a copy of the database, then system fails to create the database successfully

When user checks the checkboxes for Copy Partners and Copy User Permissions while creating a copy of the database, then system fails to create the database successfully.

Check this video for more info: http://www.screencast.com/t/zloRVJgLyD

### CODE REVIEW

**Comment by akbertram** [comment]
@bddbot  please rebuild

**Comment by akbertram** [comment]
@yuriyz It looks like this is actually a no-op?

**Comment by yuriyz** [comment]
@akbertram please check commits to branch here  : https://github.com/bedatadriven/activityinfo/commits/beta-AI-873
Problem was that I've made direct commit to beta, then reverted it and commited to beta-AI-873 branch. As result the final commit is somehow not shown in pull request but you can see it in commits.

**Comment by akbertram** [comment]
@yuriyz that's because the 'revert' (undo) commit is still in `beta` branch, so when you merge this branch into beta, the revert still gets applied and cancels out your change here. If you want to move a change from one branch to another, you have to revert on the original branch, and then _revert the revert_ on the second branch_. For example, if the change was the last to be applied to beta:

```
git checkout beta
git revert HEAD
git checkout -b beta-AI-873
git revert HEAD
```

**Comment by akbertram** [comment]
@bddbot please release

**Comment by akbertram** [comment]
Already fixed.

**Pull request closed without merging**
