### PR TITLE
AI-991 - omit saving calculated indicators 

### PR DESCRIPTION
**Pull request by yuriyz**

### CODE REVIEW

**Comment by akbertram** [comment]
Sorry if there was confusion, but it's perfectly correct for a mathematical evaluation to return a NaN: NaNs are essentially exceptions encoded into the floating point standard. The problem is that somewhere, we are trying to *persist* calculated values to the database. The problem is not specifically with NaNs, we *should not be storing any calculated values in the database*.

Please remove the exception and simply ensure that calculated values are not persisted in the database or via PersistSite or in any form.

**Comment by yuriyz** [comment]
it was never persisted.  NaN values were returned by GetSites command.

**Comment by akbertram** [comment]
GetSites should return the values as calculated, which may include NaNs. But the exception that was being thrown was in UpdateSiteHandler: https://github.com/bedatadriven/activityinfo/commit/153307d699825934d814d1b0c652c9a5bc48e5d5#diff-5f461ebc19dc333e9db7d8ceea259db5R137

The point is that calculated values produced by GetSites or other queries should *not* be sent as an update to the server.

**Comment by akbertram** [comment]
Thanks @yuriyz ,  can you merge the production branch _into_ this branch so the changes are relative to the latest version? 

Also, please replace the dbunit-based integration test with an end-to-end test in the acceptance tests module. I would prefer to avoid writing any further "unit" tests that hit the database now that we have a reasonable framework for writing end-to-end tests that provide better protection against regressions. 

You should be able to get coverage for this issue by adding a calculated indicator with division and missing values to one of the existing data entry tests. Be sure to run the test against the current version to verify that it actually fails without your fix :-)

**Comment by yuriyz** [comment]
@akbertram production is already merged to this branch. Sure, I will cover it also with acceptance test.

**Pull request merged**
